# .wav to spectrogram (Frequency Count vs Time)
# sample_rate, samples = wavfile.read('female/bfeciyuh/1.wav')
# print(samples.shape)
# frequencies, times, spectrogram = signal.spectrogram(samples, sample_rate)
# spectrogram = np.log10(spectrogram)

# plt.pcolormesh(times, frequencies, spectrogram)
# plt.imshow(spectrogram)
# plt.ylabel('Frequency [Hz]')
# plt.xlabel('Time [sec]')
# plt.show()
